codecov:
  require_ci_to_pass: true

coverage:
  status:
    project:
      default:
        target: 85%
        threshold: 2%
    patch:
      default:
        target: 80%

ignore:
  - "packages/core/src/**/index.ts"
  - "packages/core/src/abis/**"
  - "packages/core/src/types/**"
  - "packages/core/src/deploy/factories.ts"
  - "packages/sdk/src/index.ts"
  - "packages/sdk/src/types.ts"
  - "packages/sdk/src/actions/index.ts"
  - "**/*.test.ts"
  - "**/tests/**"

flags:
  core:
    paths:
      - packages/core/src/
    carryforward: true
  sdk:
    paths:
      - packages/sdk/src/
    carryforward: true
